Add ability to configure license
symfony-tools/recipes-checker pull request #1
Opened 2021-11-26 15:30 UTC by aivus

As it was mentioned in [Symfony Blog](https://symfony.com/blog/symfony-flex-is-going-serverless#custom-recipes) it's possible to re-use serverless Flex with custom recipes. To manage license checks in a flexible way it would be good to have ability to specify license from CLI.

This PR adds ability to configure license from the CLI.
Additionally it will be possible to disable license check in case you don't want to have this check (Maybe we should split it to separate command?).

2021-11-26 17:01 UTC, stof requested changes

2021-11-26 17:01 UTC, stof commented on src/LintPullRequestCommand.php
> +            ->addOption('license', null, InputOption::VALUE_OPTIONAL, 'The license to be check in PR body', 'MIT')
should be `VALUE_REQUIRED`. Your code does not handle the difference between not passing the option and passing the option with no value. And I don't think it makes sense to pass this option with no value.

In 99% of cases, using `InputOption::VALUE_OPTIONAL` is a mistake.

2021-11-26 17:07 UTC, stof commented on src/LintPullRequestCommand.php
> +            if (!preg_match('/^[ |\t]*License[ |\t]+'.$license.'[ |\t]*\r?$/mi', $data['pull_request']['body'])) {
missing `preg_quote` to escape special chars (you cannot trust an input to be already escaped for regex context)

2021-11-26 17:13 UTC, aivus commented on src/LintPullRequestCommand.php
> +            ->addOption('license', null, InputOption::VALUE_OPTIONAL, 'The license to be check in PR body', 'MIT')
I want to keep BC just in case someone is using it. So the command with `--license MIT` and w/o should work the same.

> And I don't think it makes sense to pass this option with no value.

It actually makes, and I did it intentionally to skip license check in the body if it's required.

2021-11-29 09:51 UTC, aivus commented on src/LintPullRequestCommand.php
> +            if (!preg_match('/^[ |\t]*License[ |\t]+'.$license.'[ |\t]*\r?$/mi', $data['pull_request']['body'])) {
Added `preg_quote` call

2021-11-29 09:53 UTC, stof commented on src/LintPullRequestCommand.php
> +            ->addOption('license', null, InputOption::VALUE_OPTIONAL, 'The license to be check in PR body', 'MIT')
`VALUE_OPTIONAL` is about allowing to call it as `--license` without value, which is confusing to me if the goal is to disable license checks. A `--no-license-check` flag seems a lot more understandable for that.

Also, note that code in the symfony-tools organization is not covered by any BC promise anyway, so we can change it as needed for things to make sense.

2022-02-15 10:36 UTC, nicolas-grekas approved these changes
Thank you @aivus

2022-02-15 10:37 UTC, merged