Adding linting for the new add-lines configurator
symfony-tools/recipes-checker pull request #14
Opened 2023-05-23 14:12 UTC by weaverryan

Supports https://github.com/symfony/flex/pull/975

2023-05-24 09:35 UTC, stof requested changes

2023-05-24 09:35 UTC, stof commented on src/LintManifestsCommand.php
> +                return false;
We should not return false` after the first error IMO. It is better to perform all validation in case we have multiple issues in the (missing both `file` and `content` for instance).

2023-05-24 18:38 UTC, weaverryan commented on src/LintManifestsCommand.php
> +                    $output->writeln(sprintf('::error file=%s::"add-lines" has a "%s" key but it must be a string value', $manifest, $key));
Good idea. It's a bit tricky to know WHAT to show - so I included the index integer of where this is inside of `add-lines`.

2023-05-25 12:47 UTC, stof commented on src/LintManifestsCommand.php
> +                    $output->writeln(sprintf('::error file=%s::"add-lines" has a "%s" key but it must be a string value', $manifest, $key));
yeah, I think the index is fine.

2023-05-25 12:47 UTC, stof approved these changes

2023-05-26 16:29 UTC, fabpot commented
Thank you @weaverryan.

2023-05-26 16:29 UTC, merged